In [1]:
import pandas as pd
import numpy as np
import sklearn

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Scikit-learn:", sklearn.__version__)
print("ML environment is ready!")

Pandas: 3.0.5
NumPy: 2.5.2
Scikit-learn: 1.9.0
ML environment is ready!

In [1]:
import os

ocr_folder = "../data/ocr_text"

print("Files in OCR folder:")

for file in os.listdir(ocr_folder):
    print(file)

Files in OCR folder:
invoice01.txt
marksheet01.txt
resume01.txt

In [2]:
for file in os.listdir(ocr_folder):
    file_path = os.path.join(ocr_folder, file)

    with open(file_path, "r", encoding="utf-8") as f:
        text = f.read()

    print("\n==============================")
    print("FILE:", file)
    print("==============================")
    print(text[:500])

==============================
FILE: invoice01.txt
==============================
INVOICE
Invoice Number: INV001
Date: 18 August 2026
Customer: ABC Technologies
Item: Laptop
Quantity: 1
Amount: 45000
Total: 45000


==============================
FILE: marksheet01.txt
==============================
STUDENT MARKSHEET
Student Name: Ananya Patil
Roll Number: MCA101
Python: 82
DBMS: 78
Java: 88
Data Structures: 85
Networking: 74
Total: 407
Percentage: 81.4%


==============================
FILE: resume01.txt
==============================
RESUME
Name: Rahul Sharma
Email: rahul@example.com
Education:
MCA - XYZ University
Skills:
Python
Java
SQL
HTML
CSS
Experience:
Fresher

In [3]:
import pandas as pd
import os

ocr_folder = "../data/ocr_text"

data = []

for file in os.listdir(ocr_folder):
    file_path = os.path.join(ocr_folder, file)

    with open(file_path, "r", encoding="utf-8") as f:
        text = f.read()

    if "invoice" in file.lower():
        label = "Invoice"
    elif "marksheet" in file.lower():
        label = "Marksheet"
    elif "resume" in file.lower():
        label = "Resume"

    data.append({
        "filename": file,
        "text": text,
        "label": label
    })

df = pd.DataFrame(data)

df

,filename,text,label
0,invoice01.txt,INVOICE\nInvoice Number: INV001\nDate: 18 Augu...,Invoice
1,marksheet01.txt,STUDENT MARKSHEET\nStudent Name: Ananya Patil\...,Marksheet
2,resume01.txt,RESUME\nName: Rahul Sharma\nEmail: rahul@examp...,Resume

In [4]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

df["clean_text"] = df["text"].apply(clean_text)

df[["filename", "label", "clean_text"]]

,filename,label,clean_text
0,invoice01.txt,Invoice,invoice invoice number inv001 date 18 august 2...
1,marksheet01.txt,Marksheet,student marksheet student name ananya patil ro...
2,resume01.txt,Resume,resume name rahul sharma email rahul example c...

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df["clean_text"])
y = df["label"]

print("TF-IDF shape:", X.shape)
print("Labels:", y.tolist())

TF-IDF shape: (3, 53)
Labels: ['Invoice', 'Marksheet', 'Resume']

In [6]:
features = vectorizer.get_feature_names_out()

print("Number of features:", len(features))
print("\nTF-IDF Features:")
print(features)

Number of features: 53

TF-IDF Features:
['18' '2026' '407' '45000' '74' '78' '81' '82' '85' '88' 'abc' 'amount'
 'ananya' 'august' 'com' 'css' 'customer' 'data' 'date' 'dbms' 'education'
 'email' 'example' 'experience' 'fresher' 'html' 'inv001' 'invoice' 'item'
 'java' 'laptop' 'marksheet' 'mca' 'mca101' 'name' 'networking' 'number'
 'patil' 'percentage' 'python' 'quantity' 'rahul' 'resume' 'roll' 'sharma'
 'skills' 'sql' 'structures' 'student' 'technologies' 'total' 'university'
 'xyz']

In [7]:
tfidf_df = pd.DataFrame(
    X.toarray(),
    columns=features,
    index=df["label"]
)

tfidf_df

,18,2026,407,45000,74,78,81,82,85,88,...,roll,sharma,skills,sql,structures,student,technologies,total,university,xyz
label,,,,,,,,,,,,,,,,,,,,,
Invoice,0.217408,0.217408,0.000000,0.434815,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.217408,0.165344,0.000000,0.000000
Marksheet,0.000000,0.000000,0.204585,0.000000,0.204585,0.204585,0.204585,0.204585,0.204585,0.204585,...,0.204585,0.000000,0.000000,0.000000,0.204585,0.40917,0.000000,0.155592,0.000000,0.000000
Resume,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.219607,0.219607,0.219607,0.000000,0.00000,0.000000,0.000000,0.219607,0.219607